"""Licence-aware, staging-only legal research planning."""

from .adapters import (
    FetchPlan,
    FindCaseLawMetadataAdapter,
    GenericOfficialAdapter,
    LegislationGovUkAdapter,
    OfficialSourceAdapter,
    StagedOnlineCandidate,
    adapter_registry,
)
from .control_plane import ActiveResearchSnapshot, ResearchControlPlane
from .coverage import CoverageGapDetector, SubjectCoverage
from .fetch_policy import SafeFetchPolicy
from .freshness import (
    KnowledgeEventType,
    KnowledgeFreshnessCoordinator,
    KnowledgeUpdateEventRequest,
    KnowledgeUpdateReceipt,
)
from .gap_queue import (
    GapCandidate,
    GapItem,
    GapKind,
    GapQueue,
    GapStatus,
    LegacyGapQueueReadOnlyError,
)
from .legacy import DatabaseGapCandidateSink, LegacyResearchGapImporter
from .material_updates import MaterialUpdateAssessment, MaterialUpdateGate
from .models import (
    OWNER_DECISION_REQUIRED,
    GapMateriality,
    RefinementCategory,
    ResearchCandidateDraft,
    ResearchCandidateStatus,
    ResearchDispatchResult,
    ResearchGapBindingRequest,
    ResearchPriority,
    ResearchTaskRequest,
    ResearchTaskStatus,
    ResearchTaskType,
    ResearchTrigger,
    SourceUpdateDraft,
    SourceUpdateState,
)
from .retrieval_attempt import (
    CandidateBuildBinding,
    CandidateRetrievalAttemptArtifact,
    CandidateRetrievalExecutorHit,
    CandidateRetrievalExecutorResult,
    HitQualificationDisposition,
    RankedCandidateHit,
    RetrievalAttemptArtifactRef,
    RetrievalAttemptBinding,
    execute_candidate_retrieval_attempt,
    load_verified_candidate_retrieval_attempt,
    opaque_gap_reference,
)
from .review import (
    OwnerDecisionRequired,
    ResearchCandidateOwnerView,
    ResearchReviewService,
    SourceUpdateOwnerView,
)
from .runtime import AllowlistedHttpFetcher, FetchedResponse, OfficialOnlineResearcher
from .scheduler import (
    DAILY_SCHEDULE_ID,
    WEEKLY_SCHEDULE_ID,
    ResearchScheduler,
    ScheduleTickResult,
)
from .source_registry import (
    ContentMode,
    OfficialSourcePolicy,
    OfficialSourceRegistry,
    OnlineDisposition,
    SourceLicence,
)
from .worker import (
    EncryptedResearchQuarantine,
    OfficialResearchDispatcher,
    PermanentResearchError,
    ResearchWorker,
    TransientResearchError,
)

__all__ = [
    "DAILY_SCHEDULE_ID",
    "OWNER_DECISION_REQUIRED",
    "WEEKLY_SCHEDULE_ID",
    "ActiveResearchSnapshot",
    "AllowlistedHttpFetcher",
    "CandidateBuildBinding",
    "CandidateRetrievalAttemptArtifact",
    "CandidateRetrievalExecutorHit",
    "CandidateRetrievalExecutorResult",
    "ContentMode",
    "CoverageGapDetector",
    "DatabaseGapCandidateSink",
    "EncryptedResearchQuarantine",
    "FetchPlan",
    "FetchedResponse",
    "FindCaseLawMetadataAdapter",
    "GapCandidate",
    "GapItem",
    "GapKind",
    "GapMateriality",
    "GapQueue",
    "GapStatus",
    "GenericOfficialAdapter",
    "HitQualificationDisposition",
    "KnowledgeEventType",
    "KnowledgeFreshnessCoordinator",
    "KnowledgeUpdateEventRequest",
    "KnowledgeUpdateReceipt",
    "LegacyGapQueueReadOnlyError",
    "LegacyResearchGapImporter",
    "LegislationGovUkAdapter",
    "MaterialUpdateAssessment",
    "MaterialUpdateGate",
    "OfficialOnlineResearcher",
    "OfficialResearchDispatcher",
    "OfficialSourceAdapter",
    "OfficialSourcePolicy",
    "OfficialSourceRegistry",
    "OnlineDisposition",
    "OwnerDecisionRequired",
    "PermanentResearchError",
    "RankedCandidateHit",
    "RefinementCategory",
    "ResearchCandidateDraft",
    "ResearchCandidateOwnerView",
    "ResearchCandidateStatus",
    "ResearchControlPlane",
    "ResearchDispatchResult",
    "ResearchGapBindingRequest",
    "ResearchPriority",
    "ResearchReviewService",
    "ResearchScheduler",
    "ResearchTaskRequest",
    "ResearchTaskStatus",
    "ResearchTaskType",
    "ResearchTrigger",
    "ResearchWorker",
    "RetrievalAttemptArtifactRef",
    "RetrievalAttemptBinding",
    "SafeFetchPolicy",
    "ScheduleTickResult",
    "SourceLicence",
    "SourceUpdateDraft",
    "SourceUpdateOwnerView",
    "SourceUpdateState",
    "StagedOnlineCandidate",
    "SubjectCoverage",
    "TransientResearchError",
    "adapter_registry",
    "execute_candidate_retrieval_attempt",
    "load_verified_candidate_retrieval_attempt",
    "opaque_gap_reference",
]
