# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import legalbot_model_runtime_pb2 as legalbot__model__runtime__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in legalbot_model_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LegalBotModelRuntimeStub:
    """Internal service-to-service API. The production channel is Unix-domain
    socket only and is activated only by the exact Phase-2B owner payload.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStream = channel.unary_stream(
                '/legalbot.modelruntime.v1.LegalBotModelRuntime/GenerateStream',
                request_serializer=legalbot__model__runtime__pb2.GenerateStreamRequest.SerializeToString,
                response_deserializer=legalbot__model__runtime__pb2.GenerateStreamFrame.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/legalbot.modelruntime.v1.LegalBotModelRuntime/Health',
                request_serializer=legalbot__model__runtime__pb2.HealthRequest.SerializeToString,
                response_deserializer=legalbot__model__runtime__pb2.HealthReply.FromString,
                _registered_method=True)


class LegalBotModelRuntimeServicer:
    """Internal service-to-service API. The production channel is Unix-domain
    socket only and is activated only by the exact Phase-2B owner payload.
    """

    def GenerateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LegalBotModelRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=legalbot__model__runtime__pb2.GenerateStreamRequest.FromString,
                    response_serializer=legalbot__model__runtime__pb2.GenerateStreamFrame.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=legalbot__model__runtime__pb2.HealthRequest.FromString,
                    response_serializer=legalbot__model__runtime__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'legalbot.modelruntime.v1.LegalBotModelRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('legalbot.modelruntime.v1.LegalBotModelRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LegalBotModelRuntime:
    """Internal service-to-service API. The production channel is Unix-domain
    socket only and is activated only by the exact Phase-2B owner payload.
    """

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/legalbot.modelruntime.v1.LegalBotModelRuntime/GenerateStream',
            legalbot__model__runtime__pb2.GenerateStreamRequest.SerializeToString,
            legalbot__model__runtime__pb2.GenerateStreamFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legalbot.modelruntime.v1.LegalBotModelRuntime/Health',
            legalbot__model__runtime__pb2.HealthRequest.SerializeToString,
            legalbot__model__runtime__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
